[build]
  command = "echo 'Nothing to build'"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

[context.production.environment]
  NEON_DB_URL = "postgresql://username:password@your-db.neon.tech/dbname?sslmode=require"
